name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{1123b510-f8d2-49a4-87d2-8aac3f07f3c4}}
          GH_TOKEN: ${{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}}
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
